### ISSUE TITLE
Add command line flags to define/undefine environment variables

### ISSUE THREAD

**Issue by lunixbochs** [lunixbochs/usercorn#106]
https://github.com/lunixbochs/usercorn/issues/21#issuecomment-162155091

**Comment by petevine** [comment]
Yes, qemu-user gave me the idea. It seems I made up env= , a Freudian slip :)
Thanks!

**Comment by petevine** [comment]
I'm not sure if it should go here or into the previous one as a bug but having `LD_LIBRARY_PATH` in host environment trips ld up, for instance, after `./usercorn /bin64/wc`:

````
/bin64/wc: error while loading shared libraries: /home/petevine/rust/lib/tls/x86_64/libc.so.6: invalid ELF header
````

It should simply continue to search in lib64 just like it does after unsetting this var.

**Comment by lunixbochs** [comment]
That's not a bug in Usercorn. Library searching is entirely controlled by your linker.

**Comment by petevine** [comment]
But my linker is the 32-bit version which normally needs that variable! Here we're talking about the emulated `ld-linux-x86-64` which inherits this variable as if it were the only path. This doesn't sound right to me.

**Comment by lunixbochs** [comment]
You'll need to use the "undefine environment variable" option when it exists. Still not a bug in Usercorn.

**Comment by petevine** [comment]
Adding `/lib64` as the first path solves this issue; I think the linker is very confused to print that error when the library doesn't even exist!

**Comment by lunixbochs** [comment]
fixed by 768241b10cffb0d6b8d05e9b5f8361affb52669f

**Comment by petevine** [comment]
Great, thx - it still doesn't compile though.

**Comment by lunixbochs** [comment]
You mean the MemProtect function? That was added in the upstream Unicorn repository. Do a `make get`
