### ISSUE TITLE
Unable to build any more on 32-bit Linux

### ISSUE THREAD

**Issue by petevine** [lunixbochs/usercorn#112]
I'm getting this error after issuing `make` (latest unstable):

````
# github.com/unicorn-engine/unicorn/bindings/go/unicorn
could not determine kind of name for C.uc_mem_map_ptr
make: *** [get] Error 2
````

The only place `mem_map_ptr` can be found is among unicorn python bindings - what gives?

**Comment by lunixbochs** [comment]
you need to rebuild unicorn itself, as a new api was merged

**Comment by petevine** [comment]
You might have but that's not very practical. Maybe a suggestion from the build system?

**Comment by lunixbochs** [comment]
I still disagree that's worth the added complexity.

**Comment by petevine** [comment]
Same title, new problem:

```llvm
# github.com/keystone-engine/keystone/bindings/go/keystone
../go/src/github.com/keystone-engine/keystone/bindings/go/keystone/keystone-binding.go:54: cannot convert stat_count (type *uint64) to type *C.size_t
````

**Comment by lunixbochs** [comment]
Sigh, I didn't write the keystone bindings.

**Comment by petevine** [comment]
Whose bug is it then?

**Comment by lunixbochs** [comment]
Does this fix it? https://bochs.info/p/n6wfjt

**Comment by petevine** [comment]
Yes, but it still fails later on:
`../go/src/github.com/keystone-engine/keystone/bindings/go/keystone/keystone.go:66: undefined: ks_close`

**Comment by lunixbochs** [comment]
I feel like you accidentally deleted ks_close from the end of https://github.com/keystone-engine/keystone/blob/master/bindings/go/keystone/keystone-binding.go

**Comment by petevine** [comment]
Yeah, apparently the fruit of copy/paste "patching" :) Which finally brings us back to 32-bit stuff proper:
```go
# github.com/lunixbochs/usercorn/go/arch/x86
../go/src/github.com/lunixbochs/usercorn/go/arch/x86/cgc.go:38: constant 4294967295 overflows int
../go/src/github.com/lunixbochs/usercorn/go/arch/x86/cgc.go:48: constant 4294967295 overflows int
../go/src/github.com/lunixbochs/usercorn/go/arch/x86/cgc.go:67: constant 4294967295 overflows int
````

**Comment by lunixbochs** [comment]
Oh, go replace all the instances of UINT32_MAX in that file with `-1`

**Comment by lunixbochs** [comment]
gdbstub was just merged to master and I'm about to PR https://bochs.info/p/n6wfjt - any other 32-bit issues?

**Comment by petevine** [comment]
Nah, it already built ok yesterday.

**Comment by MagaTailor** [comment]
@lunixbochs One more:
```shell
# github.com/lunixbochs/capstr ../go/src/github.com/ lunixbochs/capstr/capstr.go:72: type [16777216]C.struct_cs_insn too large
 make: *** [get] Error 2
````

**Comment by lunixbochs** [comment]
gah, I thought I'd be safe by copying the number from last time, but struct_cs_insn is too big

**Comment by lunixbochs** [comment]
it looks like it's pretty close, does 1 << 23 fix it?

**Comment by MagaTailor** [comment]
> does 1 << 23 fix it?

It does.

**Comment by lunixbochs** [comment]
pushed, thanks
