### ISSUE TITLE
32-bit ARM host support

### ISSUE THREAD

**Issue by petevine** [lunixbochs/usercorn#124]
So after a successful build of `unicorn` I've installed `go 1.5.3` on my ARM machine and tried building usercorn, which finally succeded once I've added the missing `fdset_linux_arm.go` and `timespec_linux_arm.go` files.

It seems to be fully equivalent to the 32-bit x86 version I've been using so far. Shall I create a PR?

**Comment by lunixbochs** [comment]
Sounds good to me, though if the files are equivalent between linux_i386 and linux_arm we should consider doing linux32.go with a build flag like this:

    // +build 386 arm
    // +build linux

**Comment by petevine** [comment]
Yeah, that was the easy part :) I was slightly surprised it wanted to differentiate so your solution is the most logical.

**Comment by lunixbochs** [comment]
Does 81f726cfdc997c6e9f6cfc16434817f46fea0251 work for you?

**Comment by petevine** [comment]
Yes it does so it's time to close.

**Comment by petevine** [comment]
After trying a few commands it seems `Getgid32` is an easy addition but what about `Setgid32`?
