### ISSUE TITLE
Fixed padding truncates 32-bit `uname -a`

### ISSUE THREAD

**Issue by petevine** [lunixbochs/usercorn#144]
I think I've tracked the problem to this value:

https://github.com/lunixbochs/usercorn/blob/d9dfbc1cfe30ed6445ef42b720f75b844eb0ec1b/go/kernel/linux/uname.go#L12

Any suggestions? I'd like to try tackling it myself.

**Comment by lunixbochs** [comment]
we can move that function to arch/*/linux.go and set the padding for each manually

**Comment by petevine** [comment]
I'd mindlessly tried `32` yesterday but that ate even more characters.

**Comment by lunixbochs** [comment]
From `man 2 uname`:

> The length of the fields in the struct varies.  Some operating systems or libraries use a hardcoded 9 or 33 or 65 or 257.  Other systems use  SYS_NMLN  or  _SYS_NMLN  or UTSLEN  or  _UTSNAME_LENGTH.   Clearly,  it is a bad idea to use any of these constants; just use sizeof(...).  Often 257 is chosen in order to have room for an internet hostname.

The value will likely be in /usr/include/<arch>/bits/utsname.h

**Comment by petevine** [comment]
Oh, `65` then.
