### ISSUE TITLE
Debug output missing on ARM host?

### ISSUE THREAD

**Issue by petevine** [lunixbochs/usercorn#150]
Running the command from https://github.com/unicorn-engine/unicorn/issues/421

`$ ./usercorn -v -trace busybox-i686`

```asm
+ block @0x80f7b00
                0x80f7b00: 8b44240c  
                0x80f7b04: 8d04c503000000                 eax 0xffffffff 
                0x80f7b0b:     8ee8                       eax 0xfffffffb 
                0x80f7b0b:     8ee8  
                0x80f7b0b:     8ee8  
````

doesn't look very helpful compared to the original. In other words, where's the assembly?

**Comment by lunixbochs** [comment]
Looks like capstone is broken there.

**Comment by petevine** [comment]
I built one from git, middle of November IIRC - probably not the issue here?

**Comment by petevine** [comment]
Also note there's no `+ block @0x80f7b0b`

**Comment by lunixbochs** [comment]
The issue you linked is Unicorn being buggy. It's not supposed to have a separate block at `7b0b`.

You printed a fairly reasonable Usercorn output here, but the exact spot generated by Capstone is missing. I'm extremely inclined to blame your Capstone install.

**Comment by petevine** [comment]
Sure, I meant the issue with capstone wasn't down to it being a few months old. I'll rebuild capstone first in case it's about optimizations again.

**Comment by petevine** [comment]
There was some ARM work done apparently and it works now. Great :)
