### ISSUE TITLE
install: -i unsupported flag

### ISSUE THREAD

**Issue by cyphunk** [lunixbochs/usercorn#154]
Perhaps an issue with the go installation on Ubuntu 14.04 lts?

```
~/src/unicorn/usercorn$ go build -i -o usercorn ./go/usercorn
flag provided but not defined: -i
usage: build [-o output] [build flags] [packages]
$ go version
go version go1.2.1 linux/amd64
```

**Comment by cyphunk** [comment]
The readme indicates that Go >= 1.5 required. This will probably resolve the issue, if one has the stomach to install libmono google-chrome a slew of other packages wanted with installing via packages on ubuntu

**Comment by lunixbochs** [comment]
Just use the binary distribution of Go from their website if you have problems installing your distro's package.

**Comment by cyphunk** [comment]
updating resolved the issue. thanks
