### ISSUE TITLE
require more correct paths and exec permissions to run binaries?

### ISSUE THREAD

**Issue by lunixbochs** [lunixbochs/usercorn#163]
for example: `usercorn bin` runs `./bin` first (and not path at all)

**Comment by lunixbochs** [comment]
verify against qemu, which seems kinda liberal about it

**Comment by petevine** [comment]
Is the second part about stuff like this:

`$ qemu-x86_64 ../stage0-x86_64/rustc.bin -vV`
Error while loading ../stage0-x86_64/rustc: Permission denied

`$ ./usercorn ../stage0-x86_64/rustc -vV`
invalid read: @0x40, 0x4 = 0x0

**Comment by lunixbochs** [comment]
yeah kinda. looks like qemu doesn't resolve PATH which is one of the things I thought might be wrong.

permissions are still not checked, while I assume that output is from a binary without +x?

**Comment by petevine** [comment]
Yes, I initially thought that was making a difference (I managed to see segfaults with +x) but after                        rebuilding unicorn with -g` the difference turned out to be bogus.

**Comment by lunixbochs** [comment]
fixed by 714be67f44f941bcc4ddce996ab72d29763f0628
