### ISSUE TITLE
Segfault in x86_64 backend

### ISSUE THREAD

**Issue by MagaTailor** [lunixbochs/usercorn#175]
The x86_64 version of busybox from here:

https://packages.debian.org/sid/amd64/busybox-static/download

crashes unicorn on ARM Linux:

``` shell
$ gdb --args ./usercorn busybox-x86_64-debian

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xa9788460 (LWP 23629)]
0x00000000 in ?? ()
(gdb) bt
#0  0x00000000 in ?? ()
#1  0xaca2ed3e in cpu_tb_exec_x86_64 (cpu=<error reading variable: Cannot access memory at address 0x4>, 
    tb_ptr=<error reading variable: Cannot access memory at address 0x0>)
    at /unicorn/qemu/cpu-exec.c:295
```

The older busybox binary we've been using so far works fine.

**Comment by lunixbochs** [comment]
null db in qemu sounds like a unicorn bug. Are you on the latest unicorn?

**Comment by petevine** [comment]
Probably just a few commits behind. I'll check if that makes a difference.

**Comment by lunixbochs** [comment]
Oh, that's also possibly an upstream Unicorn bug with ARM. We'll need something like #176 to properly reproduce it without Usercorn.

**Comment by lunixbochs** [comment]
What's the end of the trace look like? Mine crashes too, but in the guest instead of host:

        + block @0x401abc
          0x401abc:       4a8d4433ff lea rax, qword ptr [rbx + r14 - 1]
          0x401ac1:             31d2 xor edx, edx   rax 0xffffffffffffffff 
          0x401ac3:           4c89ff mov rdi, r15   rdx 0x0000000000000000 
          0x401ac6:           49f7f6 div r14        rdi 0x0000000000000800 

        + block @0x401ac6
          0x401ac6:           49f7f6 div r14

**Comment by petevine** [comment]
It looks like this (on ARM):

````
+ block @0x401abc
          0x401abc:       4a8d4433ff lea rax, qword ptr [rbx + r14 - 1]
          0x401ac1:             31d2 xor edx, edx   rax 0xffffffffffffffff 
          0x401ac3:           4c89ff mov rdi, r15   rdx 0x0000000000000000 
          0x401ac6:           49f7f6 div r14        rdi 0x0000000000000800 
          0x401ac6:           49f7f6 div r14
          0x401ac6:           49f7f6 div r14
````

**Comment by lunixbochs** [comment]
Yeah, looks like div r14 is broken for some reason. Working on savestate as we speak so I can repro in normal Unicorn.

**Comment by lunixbochs** [comment]
Actually r14 seems to be zero here - null division handling problem?

**Comment by lunixbochs** [comment]
Just running a `div r14` in python unicorn didn't do anything weird.

**Comment by petevine** [comment]
Btw, the binary is ok, just tried in qemu-aarch64.

**Comment by lunixbochs** [comment]
https://bochs.info/~aegis/busybox.post

**Comment by lunixbochs** [comment]
It's dividing by zero, which isn't currently handled :)

After all the trouble of writing a save format and python scripts for resuming, my python script went and printed "unhandled interrupt":

	>>> Basic block at 0x401ac6, block size = 0x36 <<<
	code 0x00401ac6,+3
	unhandled interrupt 0
	>>> Basic block at 0x401ac6, block size = 0x36 <<<
	code 0x00401ac6,+3
	unhandled interrupt 8
	>>> Basic block at 0x401ac6, block size = 0x36 <<<
	code 0x00401ac6,+3

**Comment by lunixbochs** [comment]
I just added a divide by zero handler for x86_64 linux but this is actually a different problem (the upstream eflags issue causes a div0, and this is unrelated).

**Comment by lunixbochs** [comment]
busybox-x86_64 works for me these days. Reopen this if it's still an issue.

**Comment by MagaTailor** [comment]
Busybox from the debian link? 

It still doesn't work for me (  current usercorn paired with unicorn dated 20170223)

**Comment by lunixbochs** [comment]
Forgot it was debian.

Looks like it crashes in __ctype_init, which is accessing the thread-local storage. So my guess is `arch_prctl` failed.

**Comment by lunixbochs** [comment]
Does arm unicorn still crash?

**Comment by MagaTailor** [comment]
No , it looks like this nowadays:

```asm
<< 0x471543
   0x471543: test rax, rax
   0x471546: je 0x471568

   0x471568
   0x471568: mov qword ptr [rip + 0x34ea71], rbp
   0x47156f: jmp 0x471553

   0x471553
   0x471553: mov rax, qword ptr [rbx]
   0x471556: mov qword ptr [rip + 0x34ea8b], rax            rax 0x00000000607ff131 
   0x47155d: add rsp, 8
   0x471561: pop rbx
   0x471562: pop rbp                                        rbx 0x0000000000000001 
   0x471563: ret                                            rbp 0x00000000607fedc8 

<< 0x484885
   0x484885: pop rbx
   0x484886: pop rbp                                        rbx 0x00000000004003e8 
   0x484887: pop r12                                        rbp 0x0000000000401ca0 
   0x484889: jmp 0x48eb70                                   r12 0x0000000000401d30 

<< 0x48eb70
   0x48eb70: mov rax, -0x78
   0x48eb77: mov rcx, -0x30                                 rax 0xffffffffffffff88 
   0x48eb7e: mov rax, qword ptr fs:[rax]                    rcx 0xffffffffffffffd0 
   0x48eb82: mov rdx, qword ptr [rax]                       rax 0x0000000000000000 
invalid read: @0x0, 0x8 = 0x0
[memory map]
  0xffffffffff600000-0xffffffffff601000 rwx
  0x60000000-0x60800000 rwx [stack]
  0x60800000-0x60801000 ---
  0x400000-0x5be000 r-x busybox-x86_64-debian [exe]
  0x7bd000-0x7c6000 rw- busybox-x86_64-debian [exe]
  0x7c6000-0x7c7000 rw- [brk]
  0x7c7000-0x7e8000 rw- [brk]
  0x7e8000-0x7e9000 rw- [brk]
[registers]
  rax 0x0000000000000000   rdi 0x00000000607ff131   rsp 0x00000000607fece8   r11 0x000000000000000d 
  rbp 0x0000000000401ca0   rdx 0x0000000000000000    r8 0x0000840000000000   r12 0x0000000000401d30 
  rbx 0x00000000004003e8   rip 0x000000000048eb70    r9 0x0000000000000005   r13 0x0000000000000000 
  rcx 0xffffffffffffffd0   rsi 0x0000000000000000   r10 0x0000000000420aa0   r14 0x00000000007be018 
                                                                             r15 0x0000000000000000 
[stacktrace]
  0x401540
  0x401660
  0x401807
  0x484830
  0x48eb70
panic: Invalid memory read (UC_ERR_READ_UNMAPPED)

goroutine 1 [running]:
github.com/lunixbochs/usercorn/go/cmd.(*UsercornCmd).Run(0x10714db0, 0x107105e0, 0x3, 0x4, 0x1078e400, 0x4c, 0x80)
        /home/odroid/go/src/github.com/lunixbochs/usercorn/go/cmd/cmd.go:334 +0x13b0
main.main()
        /home/odroid/usercorn-unstable/go/cmd/usercorn/main.go:12 +0x68
````

**Comment by lunixbochs** [comment]
Great, `0x48eb70` matches my `__ctype_init` function, so we're on the same page.

```
<< 0x4d8590 (__ctype_init)
   0x4d8590: mov rax, -0x78
   0x4d8597: mov rcx, -0x30                                 rax 0xffffffffffffff88 
   0x4d859e: mov rax, qword ptr fs:[rax]                    rcx 0xffffffffffffffd0 
   0x4d85a2: mov rdx, qword ptr [rax]                       rax 0x0000000000000000 
```

**Comment by lunixbochs** [comment]
If you run with -stubsys, it looks fine until it hits a NEON register access. In both arm32 and arm64, we probably need to initialize NEON.

**Comment by lunixbochs** [comment]
`__ctype_init` should be working on the `gdt` branch.

**Comment by MagaTailor** [comment]
Well done, thanks!
