### ISSUE TITLE
"criu" for debugging

### ISSUE THREAD

**Issue by lunixbochs** [lunixbochs/usercorn#176]
Have an option to dump entire CPU/memory state on exit in a way Usercorn or another Unicorn app can load/run it.

This allows me to save a Usercorn state at panic in a way the C or Python bindings can try to repro the issue.

binary format (big-endian) **NOTE: not canonical. check `go/models/savestate.go` for actual format**

```
enum(uc_arch), enum(uc_mode)
<register count>
    1: enum(reg_name), uint64(reg_val)
    2...count: repeat
<memory mapping count>
    1. uint64(addr), uint64(len), uint32(prot), <data>
    2...count: repeat
```

**Comment by petevine** [comment]
Great idea for easy upstream bug filing!

**Comment by lunixbochs** [comment]
Once it has integration with my interactive debugger it's also a sort of savestate Usercorn can reload.

**Comment by lunixbochs** [comment]
saving done (for now) in 4157c1f

**Comment by lunixbochs** [comment]
https://bochs.info/~aegis/busybox.post *shrug* :)

**Comment by petevine** [comment]
Ok, I'm trying to experiment with the funcionality and have a few questions:

- why is ` ./usercorn -savepre ls-out busybox-x86_64 ls -l` or `./usercorn -savepost ls-out busybox-x86_64 ls -l` sometimes successful but sometimes segfaults?
- nevertheless, `savepost` above prints `Warning: error saving memory at 0x100000-0x102000: Invalid memory read (UC_ERR_READ_UNMAPPED)` at the end.
- lastly, why does the command above produce 600k of output whereas the aborted run from this issue over 900k?
- runsave.py is self explanatory; is `savestate.py` just a generic mechanism for saving unicorn states, outside of usercorn?

**Comment by lunixbochs** [comment]
If your host process is segfaulting, that's almost certainly a Unicorn bug (as Go is a memory safe language).

Invalid memory read is #178 - I'm not removing a temporary memory region from my list, but it's worked around for now.

It's zlib-compressed, so the size is both based on how much memory was mapped and how compressible it was.

`savestate.py` is a module for working with savestates. It can't create them (because creating saves without the helpers provided by Usercorn is much harder), but it can read them and load them back into a Unicorn instance. If you run `savestate.py` against a savestate it will print the Unicorn parameters, registers, and memory regions.

**Comment by petevine** [comment]
Thanks!

I stopped using any special optimizations on ARM a while ago and unicorn has been stable ever since. Needs more investigation.

As for the save size, I know, but it seemed strange that a shorter execution resulted in larger size. The newer binary must be doing a lot more then.

**Comment by lunixbochs** [comment]
It's only a matter of mapped memory, it has almost nothing to do with how long the binary executes.

**Comment by petevine** [comment]
I must have wanted a replayable execution log instead :)

**Comment by lunixbochs** [comment]
#173 is along that vein. Savestates are much simpler.

**Comment by petevine** [comment]
Hey, it seems the segfaults are still their old selves, in `helper_le_ldq_mmu_x86_64` - that probably means unicorn's `release` mode (that I started using 2 days ago) turns on too much.

**Comment by lunixbochs** [comment]
closing - savestates will be removed completely in favor of #173
