### ISSUE TITLE
Performance drop emulating ARM

### ISSUE THREAD

**Issue by petevine** [lunixbochs/usercorn#182]
Let's have a look at the following comparison, running `qemu-2.5`  vs `usercorn/unicorn` on ARM:

```shell
$ time qemu-arm busybox-armv5l sha512sum ~/redox-harddrive.raw
real    0m40.549s
user    0m40.280s
sys     0m0.160
````

vs

```shell
$ time ./usercorn busybox-armv5l sha512sum ~/redox-harddrive.raw
real    1m33.913s
user    1m33.780s
sys     0m0.860s
````

Now, the `busybox-x86_64` equivalent looks like this:

````
real    0m38.001s     0m38.745s
user    0m37.820s     0m38.920s
sys     0m0.110s      0m0.570s
````
in favour of qemu, but virtually equal.

The first instance looks like a bug in `usercorn` (unless ARM emulation used to be that bad in qemu-2.2), while the second compels me to ask:
**are the unicorn's homepage claims about performance benefits from jitting actually real?**

**Comment by lunixbochs** [comment]
Interesting tests. We're on an old version of qemu which could be related. Can you test against qemu 2.2?

Either way, Unicorn is literally using the qemu JIT, so this is just a regression of some kind.

**Comment by petevine** [comment]
Ah, ok; I must have misremembered what the page **used to say**. I'll build qemu-arm 2.2.1 and see if there's any difference.

**Comment by petevine** [comment]
There it is:

```shell
$ time ./qemu-arm-2.2.1 busybox-armv5l sha512sum ~/redox-harddrive.raw
real    0m40.742s
user    0m39.170s
sys     0m0.280s
````

**Comment by lunixbochs** [comment]
Well, the x86 and ARM syscall handlers are about the same, so it's still probably a Unicorn problem.

**Comment by lunixbochs** [comment]
I just checked and arm traps don't seem to be called during the loop, so I doubt it's Usercorn's fault.

sha256sum performs about the same between armv5l and x86_64, but sha512sum is much slower on armv5l under Usercorn for me. My guess is our emulated ARM CPU has different feature flags set than qemu which give it a performance regression.

**Comment by petevine** [comment]
A lucky find then! Had I chosen sha256 we'd never have known! :)

I initially wanted to use bzip2 but that didn't work for a different reason (that I thought could be a case of WIP)

BTW, if you're looking for an ARM testing platform, look at Mini M8S TV Box from gearbest - if it could be made to run Linux that would be a hit.

**Comment by petevine** [comment]
So, do the latest additions make it possible to create a useful upstream report yet?

**Comment by lunixbochs** [comment]
need to figure out the slow part before that's useful. record/replay would make this possible but save doesn't make it easy (because it needs to make syscalls)

**Comment by petevine** [comment]
Right, I'm going to close this issue then. Let me know if you need some native testing.
