### ISSUE TITLE
Ubuntu Setup Script or Dockerfile

### ISSUE THREAD

**Issue by zachriggle** [lunixbochs/usercorn#207]
In order to facilitate easy installation by users unfamiliar with Go, Capstone, and Unicorn, a setup script (e.g. `setup.sh`) or `Dockerfile` should be provided to automate the process and set up the environment.

**Comment by lunixbochs** [comment]
WIP makefile will download and build unicorn, capstone, and keystone in-tree. I'm probably also going to add something to set up newest Go binary distribution in-tree. What are your thoughts on other OS-specific package deps? Like Keystone needs cmake, Unicorn needs a couple of misc packages.

**Comment by zachriggle** [comment]
$ apt-get build-dep

Is your friend.

**Comment by lunixbochs** [comment]
I know about apt-get build-dep. There's no apt package for Unicorn or Keystone, and I'm on OS X anyway ;)

**Comment by lunixbochs** [comment]
`make deps` just landed in unstable and should be good enough.
