### ISSUE TITLE
Signed Register Functions

### ISSUE THREAD

**Issue by afrocheese** [lunixbochs/usercorn#313]
```
git clone --depth=50 https://github.com/lunixbochs/usercorn.git usercorn
cd usercorn
git fetch origin +refs/pull/311/merge
git checkout -f FETCH_HEAD
make deps
make
$ ./usercorn run -repl bins/x86_64.darwin.macho
0x100002426> rax = -1
0x100002426> rax
0xffffffffffffffff
0x100002426> rax = 0xffffffffffffffff
could not restore rax: bad type: NaN
```
This occurs on all architectures that I have tested and also occurs using `u.reg_write`.

**Comment by lunixbochs** [comment]
I added int64 types to [luaish](https://github.com/lunixbochs/luaish) but the parser probably needs to be modified to autopromote large numbers.

**Comment by lunixbochs** [comment]
Oh! parseNumber just needs to try parsing unsigned as well.

**Comment by lunixbochs** [comment]
Fixed in https://github.com/lunixbochs/luaish/commit/50b0cd6cedf421a38f7944cf836cebcfaaa22609:

```
~/projects/luaish] ./glua
GopherLua 0.1 Copyright (C) 2015 Yusuke Inuzuka
> rax = 0xffffffffffffffff
> print(rax)
-1
> rax = 0.1
> print(rax)
0.1
> rax = 0xfffffffffffffff
> print(rax)
1152921504606846975
> 
```

Run `make get` to update the luaish dependency.

**Comment by afrocheese** [comment]
Thanks for the quick turn around! The only slightly surprising behavior that I've noticed is writing a NaN number with `u.reg_write`, but I think it might be unrelated. 
```
0x0> x0
0
0x0> u.reg_write(arm64.x0, 0xfffffffffffffffff)
0x0> x0
0x8000000000000000
```

**Comment by lunixbochs** [comment]
Huh, what happens if you set a register to like 1.5? Maybe floats shouldn’t be allowed there.

**Comment by afrocheese** [comment]
```
0x0> x0 = 1.5
could not restore x0: bad type: 1.5
0x0> u.reg_write(arm64.x0, 1.999999)
0x0> x0
1
0x0> u.reg_write(arm64.x0, -0.999999)
0x0> x0
0
0x0> u.reg_write(arm64.x0, -1.999999)
0x0> x0
0xffffffffffffffff
0x0> u.reg_write(arm64.x0, -5.999999)
0x0> x0
0xfffffffffffffffb
```
seems to more or less make sense how it handles floats
