### ISSUE TITLE
ARM does not work

### ISSUE THREAD

**Issue by lunixbochs** [lunixbochs/usercorn#52]

**Comment by lunixbochs** [comment]
partially fixed by 1a05a623639d8141bfdb8f3220be23443eb2d280 and ghostrace updates

**Comment by petevine** [comment]
Is this the expected behaviour or is it specific to my 32-bit host?

```rust
$ ./usercorn ~/Downloads/busybox-armv5l
invalid fetch: @0xffff0fe0, 0x1 = 0x0
Registers:
   r0 0xffff0fff    r4 0x0012a920    r8 0x00000000   r12 0x0012f8d4 
   r1 0x00000010    r5 0x607feb48    r9 0x00000000       0x00000000 
   r2 0x000d860c    r6 0x000080d4   r10 0x00000000       0x00000000 
   r3 0x0005239c    r7 0x00000004   r11 0x00000000       0x00000000 
Stacktrace:
  0xffff0fe0 
````

**Comment by lunixbochs** [comment]
Yeah, I get that too. armv4l gets "missing syscall" as well, which means I need to support the legacy arm SVC method (which the person working on netbsd support might contribute).

As far as armv5l, I get the same error. Looking at this trace:

        + block @0x8540
          0x8540: 0f0ae0e3 mvn r0, #0xf000
          0x8544: 1ff040e2 sub pc, r0, #0x1f         r0 0xffff0fff 

`mvn` is "move, narrowing" iirc. Is r0 supposed to be `0x0fff` here instead of `0xffff0fff`?

**Comment by petevine** [comment]
That's what bitwise NOT should be producing obviously - where do you start debugging from here?

**Comment by lunixbochs** [comment]
Ah `mvn` is MOV + NOT. My first step is to run with qemu-arm with an arm cross-gdb

    qemu-arm -g 1234 busybox-armv5l

Second terminal:

    gdb
    > target remote localhost:1234
    > b *0x8540
    > c
    > x/25i $pc
      => 0x8540:	mvn	r0, #61440	; 0xf000
      0x8544:	sub	pc, r0, #31

    > i r

      r0             0xffff0fff	4294905855
      pc             0x8544	0x8544

    > si 2
      0x000d621c in ?? ()

**Comment by petevine** [comment]
I've got qemu 2.5 on my ARM box and it definitely handles that binary well.

**Comment by lunixbochs** [comment]
0xffff0fe0 seems to be `__kuser_get_tls` on Linux

**Comment by lunixbochs** [comment]
9bf0bf6e8355dbb3393cda761c9b3a4fd432315a should have a working arm kernel trap stub, now to just implement the individual traps

**Comment by lunixbochs** [comment]
as of 0a53371423d883cd7a0aa0394c7ee5627a64c99d (still in the unstable branch), armv6 busybox help prints successfully

**Comment by petevine** [comment]
32-bit host doesn't like this :) Build fails with:

`go/arch/arm/linux.go:33: constant 4294901760 overflows int`

**Comment by lunixbochs** [comment]
Right. I need to use `~0`

**Comment by petevine** [comment]
Yes, it works meaning when trying to run busybox:

`panic: Kernel not found for syscall 'getuid32'`

From memory, I thought this one had already been implemented?

**Comment by lunixbochs** [comment]
Oh, I forgot to post that file. Just put this in `go/kernel/linux/process.go`:

    package linux

    func (k *LinuxKernel) Getuid32() int {
        return k.PosixKernel.Getuid()
    }

    func (k *LinuxKernel) Stat64() int {
        return 0
    }

**Comment by petevine** [comment]
Busybox begins to print the help, getting to

`Currently defined functions:`

and then:
````

        [, panic: runtime error: makeslice: len out of range

goroutine 17 [running, locked to thread]:
github.com/lunixbochs/usercorn/go/kernel/posix.(*PosixKernel).Write(0x18611ac0, 0x2, 0xeeead, 0x0, 0xb070b638, 0x186c20f0, 0x18867270, 0xffffffff, 0x0, 0x0, ...)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/kernel/posix/io.go:24 +0x3d
reflect.Value.call(0x829cd00, 0x82e304c, 0x13, 0x82e8278, 0x4, 0x18730b10, 0x4, 0x4, 0x0, 0x0, ...)
        /home/petevine/go/src/reflect/value.go:432 +0xee8
reflect.Value.Call(0x829cd00, 0x82e304c, 0x13, 0x18730b10, 0x4, 0x4, 0x0, 0x0, 0x0)
        /home/petevine/go/src/reflect/value.go:300 +0x8c
github.com/lunixbochs/usercorn/go/kernel/common.Syscall.Call(0x186ea150, 0x5, 0x82e28c0, 0x186c55c0, 0x16, 0x82e9868, 0x5, 0x0, 0x0, 0xb070b068, ...)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/kernel/common/call.go:62 +0x580
github.com/lunixbochs/usercorn/go.(*Usercorn).Syscall(0x186c20f0, 0x4, 0x82ebc50, 0x5, 0x186dffc0, 0x186dffc0, 0x0, 0x0, 0x0)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/usercorn.go:618 +0x41a
github.com/lunixbochs/usercorn/go/arch/arm.LinuxSyscall(0xb070b638, 0x186c20f0, 0x4)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/arch/arm/linux.go:77 +0xc6
github.com/lunixbochs/usercorn/go/arch/arm.LinuxInterrupt(0xb070b638, 0x186c20f0, 0x2)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/arch/arm/linux.go:97 +0x19e
github.com/lunixbochs/usercorn/go.(*Usercorn).addHooks.func5(0xb070b5b8, 0x186c5590, 0x2)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/usercorn.go:462 +0x53
github.com/unicorn-engine/unicorn/bindings/go/unicorn.hookInterrupt(0xb0f47158, 0x2, 0x1872df10)
        /home/petevine/go1.5/src/github.com/unicorn-engine/unicorn/bindings/go/unicorn/hook.go:45 +0x64

goroutine 1 [syscall, locked to thread]:
github.com/unicorn-engine/unicorn/bindings/go/unicorn._Cfunc_uc_emu_start(0xb0f47158, 0x81d0, 0x0, 0xffffffff, 0xffffffff, 0x0, 0x0, 0x0, 0x0)
        github.com/unicorn-engine/unicorn/bindings/go/unicorn/_obj/_cgo_gotypes.go:125 +0x37
github.com/unicorn-engine/unicorn/bindings/go/unicorn.(*uc).StartWithOptions(0x186c5590, 0x81d0, 0x0, 0xffffffff, 0xffffffff, 0x1864fb30, 0x0, 0x0)
        /home/petevine/go1.5/src/github.com/unicorn-engine/unicorn/bindings/go/unicorn/unicorn.go:82 +0x6c
github.com/unicorn-engine/unicorn/bindings/go/unicorn.(*uc).Start(0x186c5590, 0x81d0, 0x0, 0xffffffff, 0xffffffff, 0x0, 0x0)
        /home/petevine/go1.5/src/github.com/unicorn-engine/unicorn/bindings/go/unicorn/unicorn.go:87 +0x72
github.com/lunixbochs/usercorn/go.(*Usercorn).Run(0x186c20f0, 0x1860a188, 0x1, 0x1, 0x186ca000, 0x37, 0x40, 0x0, 0x0)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/usercorn.go:177 +0xe15
main.main()
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/usercorn/cli.go:168 +0x134f

goroutine 18 [syscall, locked to thread]:
runtime.goexit()
        /home/petevine/go/src/runtime/asm_386.s:1662 +0x1
````

**Comment by lunixbochs** [comment]
Update dependencies. This might be related to the argjoy and struc changes I did recently.

**Comment by petevine** [comment]
I thought they were being updated on every `make`? 

-original message-
Subject: Re: [usercorn] ARM does not work (#52)
From: Ryan Hileman <notifications@github.com>
Date: 16.01.2016 00:22

Update dependencies. This might be related to the argjoy and struc changes I did recently.

---

**Comment by lunixbochs** [comment]
They should, but I had some errors similar to the one you see and since fixed them, and it currently works on my machine. I'll try a 32-bit system later.

**Comment by petevine** [comment]
Do you want me to create a PR with these changes/additions?

**Comment by lunixbochs** [comment]
The ARM tweaks I suggested? They're already in unstable.

**Comment by petevine** [comment]
I don't see any new commits since the problems with 32-bit host were fixed so I thought you were simply too busy.

-original message-
Subject: Re: [usercorn] ARM does not work (#52)
From: Ryan Hileman <notifications@github.com>
Date: 17.01.2016 00:00

The ARM tweaks I suggested? They're already in unstable.

---

**Comment by lunixbochs** [comment]
They were old commits I hadn't pushed yet.

**Comment by petevine** [comment]
OK, so after the latest changes, on `x86` host, busybox-armv5 prints the whole help but ends in:

```rust
invalid fetch: @0x400001d0, 0x1 = 0x0
Registers:
   r0 0x00000000    r4 0xffffffff    r8 0x00000000   r12 0x607fe838 
   r1 0x00000001    r5 0x0012a920    r9 0x00000000       0x00000000 
   r2 0xffffffb8    r6 0x0012a8d8   r10 0x00000000       0x00000000 
   r3 0x400001d0    r7 0x00000006   r11 0x00000000       0x00000000 
Stacktrace:
  0x400001d0
````

I saw the same error earlier on the newly minted ARM host but clearly it's not specific to that platform.

**Comment by lunixbochs** [comment]
Yep, this happens for me too. Haven't debugged it yet.

**Comment by lunixbochs** [comment]
All of the helpers are implemented. Closing this in favor of a new bug complaining about the invalid fetch on exit.
