### ISSUE TITLE
Install documentation Go version

### ISSUE THREAD

**Issue by ranmrdrakono** [lunixbochs/usercorn#68]
It seems usercorn needs go1.5 since most repos contain older versions, it should probably be stated somewhere in the readme

**Comment by lunixbochs** [comment]
do you know what in usercorn depends on Go 1.5? I didn't consciously use any 1.5 features.

**Comment by ranmrdrakono** [comment]
```
go/models/arch.go:37: undefined: strings.Compare
```

**Comment by lunixbochs** [comment]
removed `strings.Compare()` usage

**Comment by lunixbochs** [comment]
Fixed by 955db35cb3db29f0d3da846e89b6a3df1ac62e67 and the travis branch merge (Go down to 1.2 is definitely supported, and 1.1 could be supported with patches to the upstream Unicorn and Capstone bindings)
