### ISSUE TITLE
go get error 

### ISSUE THREAD

**Issue by Noiled** [lunixbochs/usercorn#84]
go version go1.5.1 darwin/amd64

when type
     go get github.com/lunixbochs/usercorn/go/usercorn 

get an error 

work/go/src/github.com/bnagy/gapstone/arm64_constants.go:22:11: fatal error: 'capstone/capstone.h' file not found
 #include <capstone/capstone.h>

what's wrong?

**Comment by lunixbochs** [comment]
You need capstone. I'll update the README.

**Comment by Noiled** [comment]
@lunixbochs ths
