### ISSUE TITLE
Can't build on 32-bit x86

### ISSUE THREAD

**Issue by petevine** [lunixbochs/usercorn#99]
Hi,

This is my first contact with Go so I'm not sure I can vouch for my installation but hopefully that's not the issue here:

````
go build -i -o usercorn ./go/usercorn

# github.com/lunixbochs/usercorn/go/native
../../go1.5/src/github.com/lunixbochs/usercorn/go/native/fdset_linux.go:16: cannot use f.To64() (type [16]int64) as type [32]int32 in field value
../../go1.5/src/github.com/lunixbochs/usercorn/go/native/select_linux.go:9: cannot use int64(timespec.Sec) (type int64) as type int32 in field value
../../go1.5/src/github.com/lunixbochs/usercorn/go/native/select_linux.go:9: cannot use int64(timespec.Nsec / 1000) (type int64) as type int32 in field value
````

There's a TODO comment in `select_linux.go` so in case 32-bit support is not finished yet at least be aware I'm interested in doing some testing :)

**Comment by lunixbochs** [comment]
Wait, people use 32-bit x86 Linux still? :D I'll take a look.

**Comment by petevine** [comment]
You're probably thinking pentium mmx or sth - don't forget about the relatively recent 32-bit Atom cpus so it's not such a far-fetched use case :)

**Comment by lunixbochs** [comment]
Try the current unstable branch. You should probably find GOPATH/src/github.com/lunixbochs/usercorn and symlink it to your cloned directory (or just work out of GOPATH) to make local changes and branches work properly.

**Comment by petevine** [comment]
Sorry if I'm not doing this right but I'm still getting the last 2 errors:

````
go/native/select_linux.go:9: cannot use int64(timespec.Sec) (type int64) as type int32 in field value
go/native/select_linux.go:9: cannot use int64(timespec.Nsec / 1000) (type int64) as type int32 in field value
````

Was the fdset patch supposed to take care of those as well?

**Comment by lunixbochs** [comment]
oh, didn't see the timespec errors. those should be fixed too in latest unstable.

**Comment by petevine** [comment]
Ok, there's another one:

````
# github.com/lunixbochs/usercorn/go/kernel/posix
go/kernel/posix/time.go:15: cannot use ts.Sec (type int32) as type int64 in field value
go/kernel/posix/time.go:15: cannot use ts.Nsec (type int32) as type int64 in field value
````

**Comment by lunixbochs** [comment]
Alright, new commit in unstable.

**Comment by petevine** [comment]
Thanks, that was the last one :)

What's the reason `ld` is being run instead of the executable given on the command line?

**Comment by lunixbochs** [comment]
When you run a dynamically linked binary, the PT_INTERP ELF header can be used to specify an "interpreter" binary. This is usually used to indicate it uses a dynamic linker.

ld.so is the dynamic linker. When running a 32-bit x86 binary, I don't think I currently pass the auxv header necessary to initialize ld.so, so it prints usage information.

https://github.com/lunixbochs/usercorn/blob/master/go/arch/x86_64/linux.go#L52
https://github.com/lunixbochs/usercorn/blob/master/go/arch/x86/linux.go#L19

**Comment by petevine** [comment]
Thanks for the detailed explanation. I know what ld is of course (have had some experience with qemu-i386 anyway) and already tested the simple bundled binaries but was probably expecting too much from the newly supported arch :)

-original message-
Subject: Re: [usercorn] Can't build on 32-bit x86 (#99)
From: Ryan Hileman <notifications@github.com>
Date: 20.11.2015 16:35

When you run a dynamically linked binary, the PT_INTERP ELF header can be used to specify an "interpreter" binary. This is usually used to indicate it uses a dynamic linker.

ld.so is the dynamic linker. When running a 32-bit x86 binary, I don't think I currently pass the auxv header necessary to initialize ld.so, so it prints usage information.

https://github.com/lunixbochs/usercorn/blob/master/go/arch/x86_64/linux.go#L52
https://github.com/lunixbochs/usercorn/blob/master/go/arch/x86/linux.go#L19

---

**Comment by lunixbochs** [comment]
Give me about five minutes.

**Comment by lunixbochs** [comment]
The stack-init branch at 9ac8751 should support 32-bit Linux auxv (not merged to unstable yet because I broke MachO binary loading)

Keep in mind #21 is still unfinished - glibc/musl can't successfully init yet on x86_64, not sure about i386.

**Comment by petevine** [comment]
Give me about 2 hours and I'll report back about i386.
Thanks! 

-original message-
Subject: Re: [usercorn] Can't build on 32-bit x86 (#99)
From: Ryan Hileman <notifications@github.com>
Date: 20.11.2015 17:16

The stack-init branch at 9ac8751 should support 32-bit Linux auxv (not merged to unstable yet because I broke MachO binary loading)

Keep in mind #21 is still unfinished - glibc/musl can't successfully init yet on x86_64, not sure about i386.

---

**Comment by lunixbochs** [comment]
Merged stack-init. Just use unstable now.

**Comment by petevine** [comment]
Hey, look at this, I may have been wrong about 32-bit:

http://hothardware.com/news/jaguarboard-intel-atom-powered-single-board-mini-pc-to-take-on-raspberry-pi-at-45
